#' add plausible weight (by scenario and week)
#'
#' @param proj data.table containing projections to determine plausibility
#' @param variant_takeover vector with dates of each variant takeover (names of
#'        vector are names of variant)
#' @param keep_flags logical TRUE to keep the "plaus_scenario" and `plaus_week`
#'        flags generated by helper functions
#'
#' @return proj data.table containing projections with column for scenario plausibility
#'
#' @export
add_plaus_weight <- function(proj, variant_takeover, keep_flags = FALSE){
  proj <- plaus_weight_by_scenario(proj = proj)
  proj <- plaus_weight_by_week(variant_takeover = variant_takeover,
                               proj = proj)
  # combine flags
  proj <- proj[, plaus_weight := ifelse(plaus_week == 0, 0, plaus_scenario)]
  if(!keep_flags){
    proj <- proj[, ":=" (plaus_scenario = NULL,
                         plaus_week = NULL)]
  }
  return(proj)
}


#### HELPERS -------------------------------------------------------------------

#' add plausible weight by scenario
#'
#' @param p string location of file that specifies plausible weight of each scenario
#' @param proj data.table containing projections to determine plausibility
#'
#' @return proj data.table containing projections with column for scenario plausibility
#'
#' @export
plaus_weight_by_scenario <- function(p = "code/evaluation/data/MostPlausibleScenarios.csv",
                                     proj){
  plaus <- setDT(read.csv(p)) %>%
    .[,c("round", "A", "B", "C", "D")] %>%
    .[,':=' (round = as.double(round),
             A = as.double(A),
             B = as.double(B),
             C = as.double(C),
             D = as.double(D))] %>%
    data.table::melt("round", variable.name = "scenario", value.name = "plaus_scenario") %>%
    setnames(old = "scenario", new = "scenario_letter")
    proj <- plaus[proj[, scenario_letter := substr(scenario_id, 1,1)], on = .(scenario_letter, round)] %>%
      # set plaus weights to 1 for null models
      .[, ":=" (plaus_scenario = ifelse(substr(model_name,1,4) == "null", 1, plaus_scenario))]
    proj <- proj[ , scenario_letter := NULL]
    return(proj)
}

#' add plausible weight by week
#'
#' @param variant_takeover vector with dates of each variant takeover (names of vector are names of variant)
#' @param proj data.table containing projections to determine plausibility
#'
#' @return proj data.table containing projections with column for scenario plausibility
#'
#' @export
plaus_weight_by_week <- function(variant_takeover,
                                     proj){
  proj <- proj[, plaus_week := ifelse(round == 1 &
                                        target_end_date >= as.Date(variant_takeover_date["alpha"]),
                                      0, 1)]
  proj <- proj[, plaus_week := ifelse(round %in% 1:5 &
                                        target_end_date >= as.Date(variant_takeover_date["delta"]),
                                      0, plaus_week)]
  proj <- proj[, plaus_week := ifelse(round %in% 1:10 &
                                        target_end_date >= as.Date(variant_takeover_date["omicron"]),
                                      0, plaus_week)]
  return(proj)
}

